.TH sem_destroy 3 "22 de Noviembre de 2006" "Versión 1.0" "Minix programmer's manual"

.SH NOMBRE

.B sem_destroy
\- destruye un semáforo no nombrado

.SH SINOPSIS
.B #include <semaphore.h>

.B int sem_destroy(sem_t *sem);

.SH DESCRIPCION
La función sem_destroy destruirá el semáforo indicado por sem. Sólo un semáforo creado utilizando sem_init puede ser destruido por sem_destroy; el efecto de llamar sem_destroy con un semáforo no nombrado es indefinido, al igual que el uso subsecuente del semáforo hasta que se lo re-inicialice nuevamente.

Es seguro destruir un semáforo inicializado sobre el cual no haya threads actualmente bloqueados. El efecto de destruir un semáforo donde hayan threads bloqueados es indefinido.

.SH VALOR DE RETORNO
Ambas funciones, en una ejecución exitosa se devolverá el valor cero. En caso de error se devolverá -1 y la variable errno será actualizada para indicarlo.

.SH CONFORME A
POSIX.

.SH VER TAMBIÉN
.B sem_close
(3),
.B sem_getvalue
(3), 
.B sem_init
(3), 
.B sem_open
(3),
.B sem_post
(3),
.B sem_timedwait
(3), 
.B sem_trywait
(3),
.B sem_unlink
(3),
.B sem_wait
(3)

